<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="19190" started-at="2019-05-27T07:15:47Z" finished-at="2019-05-27T07:16:07Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="19190" started-at="2019-05-27T07:15:47Z" finished-at="2019-05-27T07:16:07Z">
      <class name="Testng.Demo2">
        <test-method status="FAIL" signature="launch()[pri:0, instance:Testng.Demo2@67117f44]" name="launch" duration-ms="7028" started-at="2019-05-27T12:45:47Z" finished-at="2019-05-27T12:45:54Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Sujatha] but found [OrangeHRM]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Sujatha] but found [OrangeHRM]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at Testng.Demo2.launch(Demo2.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method status="PASS" signature="testcase()[pri:0, instance:Testng.Demo2@67117f44]" name="testcase" duration-ms="11878" started-at="2019-05-27T12:45:54Z" depends-on-methods="Testng.Demo2.launch" finished-at="2019-05-27T12:46:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="xend()[pri:0, instance:Testng.Demo2@67117f44]" name="xend" duration-ms="250" started-at="2019-05-27T12:46:06Z" depends-on-methods="Testng.Demo2.testcase" finished-at="2019-05-27T12:46:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- xend -->
      </class> <!-- Testng.Demo2 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
